# Generated by Django 2.2 on 2023-08-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immin', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
