# Generated by Django 2.2 on 2023-08-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immin', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='post_pics'),
        ),
    ]
